monitoring.enabled=true
monitoring.http.port=8080
monitoring.http.token=CHANGE_ME_USE_A_UUID

# From @BotFather and @userinfobot
monitoring.telegram.botToken=8673220617:AAFWPVSo36pf3dZoNGmNAqMoe2jisLJPRgE
monitoring.telegram.chatId=250289304
monitoring.telegram.commands.enabled=true
